### PR TITLE
Responsive nomnichi

### PR DESCRIPTION
**Pull request by oppapili**
#9 に対する PR．
- 画面が小さいとき，navbarの内容をToggleできるようにした．（全ページ）
- 画面が小さいとき，デフォルトのsidebarを隠し，modal版sidebar表示のためのボタンを見せるようにした．（article/index）

今後やるかやらないか悩んでいる項目
- Sidebar をshowにもつけるか．
- app/view/layout/nomnichi を作成してarticle/index と show に適応するか．
- renderなどを使ったコードのリファクタリング

### CODE REVIEW

**Comment by yoshinari-nomura** [comment]
Why modal?
Please do not abuse modal window.

**Comment by okada-takuya** [comment]
> Why modal?
I could not think other good way...
Do you have good example?

**Comment by okada-takuya** [comment]
I had some idea for show side bar menu in small window.

1. modal side bar
1. place side bar contents to navbar.
    + https://codyhouse.co/demo/responsive-sidebar-navigation/index.html#0
1. extend side bar vertically in medium and large window and enable to toggle it in any size window.

**Comment by yoshinari-nomura** [comment]
Actually, I did not check your code, but maybe offcanvas is a good candidate I believe.
  https://getbootstrap.com/examples/offcanvas/
I used it once for my personal expense app and I preferred it.

**Comment by okada-takuya** [comment]
Thank you for your suggestion.
I will check that and implement.

**Comment by okada-takuya** [comment]
I re-implemented sidebar using offcanvas.

In a small size view, the sidebar is shown like this.



In a extra small size view, the sidebar is hided and the button for toggling sidebar is shown like this.



When users click this button, sidebar is shown .

**Pull request merged**
